### ISSUE TITLE
Stdlib build dependence check failure: does not detect updated ScalarIO.sac

### ISSUE THREAD

**Issue by bernecky** [SacBase/Stdlib#46]
When I change ScalarIO.sac, the build code fails to detect that
change, so it does not recompile ScalarIO.sac. 

`touch *` in that folder does not help.
`cmake .. ; make -j `
in the build folder does not help, either.

I have to do:
 ```
  make clean
  make -j
  sudo make install

```
to get the code compiled and available for use.

**Comment by hv15** [comment]
Yes this is a bit tricky to make working given how we have setup the build system. The issue is that we don't have a complete overview of source file dependencies --- we instead depend on targets which are used to generate the shared library files. What this means through is that we stupidly only look to see if the shared library exists, and move on. We do not check if its source has changed *and* we do not check if a dependency for a given shared library has changed, meaning re-compilations don't even propagate to other targets.

Why did we do this? Well if my memory isn't too fuzzy (@ashinkarov correct me if I'm wrong), we did initially setup the build system to follow source file dependencies, this though would on occasion cause the entire stdlib to be rebuilt due to how timestamps are handled in CMake.

Your workaround is one solution. The other is to go into `build-dir/lib/` and manually remove all the host modules there which one want to re-compile, and then call `make`.

Maybe there is a way to add source file dependencies to the targets, but we have to do this _after_ generating the targets. Hmmm...

**Comment by ashinkarov** [comment]
It is surprising that nobody noticed this before.
@hv15 , I think this is just a bug, as we are missing the source dependency when we are building modules, so the fix would be just to add it.

**Comment by bernecky** [comment]
As of commit d6b18d1, the failure to detect changed ScalarIO.sac is still there.

**Comment by hv15** [comment]
We have PR #46 for this, I think there was one more change needed before we can merge this in.

**Comment by bernecky** [comment]
Still broken as of: 1d480c66abb62a047b5e26584e47b47b52223073

**Comment by hv15** [comment]
@bernecky I tried your example and any change to source files now leads to rebuild of dependents.

**Comment by bernecky** [comment]
This looks to be resolved correctly, Hans. The touch/make thing now properly rebuilds ScalarIO.sac, etc.
I did have to do "git submodule update" to pick up those changes.
